fix: add max_nodes_per_hop parameter and fix file_paths reference
Added missing max_nodes_per_hop parameter that graph_sampler.py expects.

Also fixed SubgraphDataset call to use params.file_paths instead of
undefined pool_file_paths variable.

Fixes:
- AttributeError: 'Namespace' object has no attribute 'max_nodes_per_hop'
- NameError: name 'pool_file_paths' is not defined